[workspace]
members = [
    "spector_core",
    "spector_daemon",
    "spector_client"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Spector Developer"]

[workspace.dependencies]
# UI / Graphics (Used by Client)
eframe = "0.34.1"
wgpu = "29"
colorous = "1.0"

# DSP / Audio (Used by Daemon)
rustfft = "6.1"
libpulse-binding = "2.28"
libpulse-simple-binding = "2.28"
pipewire = "0.9.2"

# IPC & Memory (Used by both)
memmap2 = "0.9.3"
bytemuck = { version = "1.14", features = ["derive"] }